### PR TITLE
Kid Section Added

### LINKED ISSUE #324: Feature:Adding child section
Adding items for children will enhance this.I want to add section for children.Plzz assign me this issue.I want to contribute in your project.

### PR DESCRIPTION
**Pull request by TanviGandhotra**
1.Updated Dropdwon
image
2.On clicking Kid section
image
3.Created diff section for boys as by default u will go to girl kid section
image

Hope u like my work.This is done under gssoc-ext and hacktoberfest
Closes #324

### CODE REVIEW

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Review by Tejashri-Taral — COMMENTED** [review]
Awesome

**Comment by TanviGandhotra** [comment]
@Tejashri-Taral thnku so much.Plzz assign level also which u think i deserve.

**Comment by Tejashri-Taral** [comment]
@TanviGandhotra Make sure when you raise pr mention issue no. too in future contribution!
I liked your work.

**Comment by TanviGandhotra** [comment]
oh ok @Tejashri-Taral  its my first accepted hactoberfest and gssoc-ext pr so happy..

**Pull request merged**
