### PR TITLE
Fixed the appearance and response of nav bar

### LINKED ISSUE #35: Enhance the appearance and response of the nav bar.
**Describe the issue**
The nav bar can be made more interactive and also its appearance can be enhanced to make it look more appealing.

{5CC6FAC0-7C4D-4E10-8349-D4D0FDE4C224}

### PR DESCRIPTION
**Pull request by arcane-2004**
## What does this PR do?

Updated the navbar with a black background and gold/orange text and icons, adding a hover effect that increases the text size for an interactive experience.

Fixes #35 

image

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
This design doesn't follow the website theme. 
can you do some other improvements

**Comment by arcane-2004** [comment]
Do you want me to change the black background of the nav bar??

**Comment by arcane-2004** [comment]
If you have some idea of any color combination,  please do let me know.

**Review by Tejashri-Taral — APPROVED** [review]
Approved

**Pull request merged**
