### PR TITLE
Update and Enhancement of UI

### PR DESCRIPTION
**Pull request by KRISHkg31**
Updation: Removal of the Dark Mode toggle button, as the website’s UI is already in black and white. Keeping the Dark Mode button would reduce the visibility of the website logo and complicate other design elements.

After the Changes:- 
image

Enhancement :- 
1. There were a few issues with the UI. The first one was that the visitor counter was not properly positioned and was overlapping the LinkedIn and GitHub logos, so I fixed its placement.
 
Before the Changes:- 
image

After the Changes:- 
image

2. The second issue was on the Contact Us page, where two 'scroll to top' buttons appeared when the user scrolled down the page. I have fixed this as well.

Before the Change:- 
image

After the Change:- 
image

### CODE REVIEW

**Comment by KRISHkg31** [comment]
@Tejashri-Taral I have enhance the Vsitor count button and also done some addition in the Dark Mode button and Scroll to top button please have a look and let me know if anything else needed. Request you to please merge the PR.
Thank You

**Comment by Tejashri-Taral** [comment]
Mention issue no.

**Comment by KRISHkg31** [comment]
Issue No. - #807

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by Tejashri-Taral** [comment]
Please resolve the conflicts

**Comment by KRISHkg31** [comment]
@Tejashri-Taral Resolved all the conflicts

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
