### PR TITLE
FAQ animated and hover design added in FAQ page

### PR DESCRIPTION
**Pull request by Subham1**
issue #485 
#439 

The FAQ page has been enhanced with hover animations. When users hover over a question, it changes color and weight, making it more engaging and easier to navigate. This improvement adds a dynamic touch to the page while helping users find answers quickly.

https://github.com/user-attachments/assets/58a96453-6d32-4e35-96ed-455fecde31f5

### CODE REVIEW

**Comment by Subham1** [comment]
@Tejashri-Taral based on requirement i have made the changes
 kindly label gssoc with best level to this issue and merge my PR

**Review by hars-21 — CHANGES_REQUESTED** [review]
image


Keep the styles like this and add hover effect to this only. Also try to enhance container as box shadow is not visible.

**Review by Tejashri-Taral — COMMENTED** [review]
After reviewing the code, I came to know that you used the "Format code" of vs code which just increased the no. of lines changed.   
As the FAQ section is already there and you are assigned you could have added some new questions to it. 

hence I am unassigning you and closing this PR.

**Comment by Tejashri-Taral** [comment]
i am closing this PR for these reasons. 
You can still find and raise new issues

**Pull request closed without merging**
