### PR TITLE
Subscribe to Newsletter Buttons Alignment Fixed

### PR DESCRIPTION
**Pull request by ParasY1724**
**Issue No**:#5
**Changes Done :**

1. Added Flex Column
2. Alignment Fixed
3. Input Type Changed From text to email
4. Added Placeholder

**Before:**
Screenshot From 2024-10-01 18-32-32
**After:**
Screenshot From 2024-10-01 22-56-56

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Replace dummy text (Maxime quae inventore sunt odio perspiciatis vitae saepe officia dolorem.) with something good and also add hovering effect on 'subscribe' button

**Comment by ParasY1724** [comment]
**Done**
1.Added Hover over the button
2.Replaced Dummy Text
Screenshot From 2024-10-02 01-18-26

**Comment by ParasY1724** [comment]
> Replace dummy text (Maxime quae inventore sunt odio perspiciatis vitae saepe officia dolorem.) with something good and also add hovering effect on 'subscribe' button


**Done**
1.Added Hover over the button
2.Replaced Dummy Text
Screenshot From 2024-10-02 01-18-26

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts.

**Comment by ParasY1724** [comment]
> Please resolve conflicts.

@Tejashri-Taral Done !!

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
