### PR TITLE
Added feedback option.

### PR DESCRIPTION
**Pull request by Kajalmehta29**
I have added feedback option at the footer part so as to take reviews from the customer.
issue resolved: #137

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Can you please add screenshot or video as I'm not able to see it

**Comment by Kajalmehta29** [comment]
Screenshot 2024-10-05 193554

Please have a look. As a beginner i tried my best.

**Comment by Kajalmehta29** [comment]
Screenshot 2024-10-05 194755

**Comment by Kajalmehta29** [comment]
Please have a look. As a beginner i tried my best.
Thankyou.

**Comment by Tejashri-Taral** [comment]
image

**Comment by Tejashri-Taral** [comment]
We don't need feedback form in the footer itself.
Also you added it in the about.html footer...which is unnecessary

Please make the form above the footer in the home page 
Or
Make a separate page for feedback form and link it in the footer as "feedback"

**Comment by Tejashri-Taral** [comment]
You can make a new PR

**Pull request closed without merging**
