### PR TITLE
improve scroll bar and preloader

### PR DESCRIPTION
**Pull request by VidhanThakur09**
### Related Issue

Issue Fixed: #237 

### Description

Styling has been applied to the preloader and scroll bar. The preloader and Scroll bar is present on all pages of the website with styling. The scroll bar behaviour has been improved and the thumb and track have been redesigned, resulting in improved scroll behaviour.

*Improvements:*

1. *Optimized Preloader:* Enhanced the preloader animation on the landing, Boy, about, child, contact, features, login-signup, mens, and womens pages to improve user experience.

2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.

3. *Dedicated Preloader Script and StyleSheet:* Created a separate JavaScript file named `"preloader.js"` to manage the preloader functionality and CSS file named `" preloaderStyle.css"` to enhance the styling and functionality, ensuring better code organization and maintainability.

## How Has This Been Tested? 

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Screenshots 📷

**Before changes** 

https://github.com/user-attachments/assets/0ac668f5-fa72-4fe5-bcce-50922a8e26af

**After adding preloader**

https://github.com/user-attachments/assets/45f3ae4f-a598-4b3d-96a4-c0e2f57e10f5

**After improving scroll bar**

https://github.com/user-attachments/assets/3594f5db-aea0-441c-a6af-7a78231114b0

@Tejashri-Taral    could u please add suitable levels to the PR, as I have added a Scroll bar and designed PreLoader and add on all the pages with styling?

### CODE REVIEW

**Review by hars-21 — APPROVED** [review]

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral could you please increase the level for this PR as preloader is design from scratch and been added on all the pages.

**Comment by VidhanThakur09** [comment]
@Tejashri-Taral Hello,

I would like to kindly request if you could please consider increasing the level of this pull request.

Thank you for your time and consideration.

**Comment by Tejashri-Taral** [comment]
@VidhanThakur09 Good!

**Comment by VidhanThakur09** [comment]
thank you mam

**Pull request merged**
