### PR TITLE
UI Fixes on the main page .

### LINKED ISSUE #613: [Bug]: Some UI fixes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The font-family written with the images is not consistent with the overall font family and it looks a bit odd. Please assign this to me to fix it under hacktoberfest and gssoc-ext. 

### Add Screenshots / Video Clip

image

### What browsers are you seeing the problem on?

_No response_

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by pbln**
Fixes #613 
I made some basic UI fixes that includes: 
1. Scroll Animation 
2. Changed font family on buttons on the feature section 
3. Changed background color to match the grey white theme of the site . 

image
This is how it looks .
Thank you .

### CODE REVIEW

**Comment by pbln** [comment]
@Tejashri-Taral can you pls check this?

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by pbln** [comment]
@Tejashri-Taral can you add hacktoberfest label too?

**Comment by Tejashri-Taral** [comment]
Hacktoberfest is ended now

**Comment by pbln** [comment]
but like i created this pr before it ended and submitted my work also before that , so like can't it be assigned the label, since like I lag only one of the 4 contributions that need to be accepted so..? ?

**Pull request merged**
