### PR TITLE
add tooltips on the contact form

### PR DESCRIPTION
**Pull request by efshaperveen**
https://github.com/user-attachments/assets/13c285a7-12f2-4ddc-a09a-22a7775c4956

### CODE REVIEW

**Review by hars-21 — CHANGES_REQUESTED** [review]
Make the tooltips aligned with the input. Try to improve design

**Comment by efshaperveen** [comment]
Ok

**Comment by efshaperveen** [comment]
https://github.com/user-attachments/assets/c6eac6fb-2713-4d41-b8be-5bb7ee071ebb

**Comment by efshaperveen** [comment]
hello,ma'am                                                                                                                                                                                            I changed the reguest,please check it out

**Comment by hars-21** [comment]
@Tejashri-Taral Please check the UI part. If you are okay with it then you can merge this PR.

**Review by hars-21 — APPROVED** [review]

**Comment by efshaperveen** [comment]
Ok, thanks

**Comment by efshaperveen** [comment]
How I can merge it ?

**Comment by efshaperveen** [comment]
ok ma'am
thanks

**Pull request merged**
