### PR TITLE
ALIGN AND ENHANCE ALL PRODUCTS IN WOMENS BOY'S & CHILD'S PAGES

### PR DESCRIPTION
**Pull request by laxmikandivalasa**
earlier the pr num #362  has been closed 
therefore enhanced kids section too

Screenshot (278)
Screenshot (279)

### CODE REVIEW

**Comment by hars-21** [comment]
@laxmikandivalasa Please resolve the merge conflicts

**Comment by laxmikandivalasa** [comment]
@hars-21 Is it okay now??

**Comment by laxmikandivalasa** [comment]
I wish you add level 3 tag

**Comment by laxmikandivalasa** [comment]
since I'm new to this contribution
can you let me know
should I send the pr again?

**Comment by Tejashri-Taral** [comment]
Yes, you can make new pr or change some piece of code it will reflect here

**Comment by laxmikandivalasa** [comment]
@Tejashri-Taral updated all the 3 files
you can check now!

**Comment by Tejashri-Taral** [comment]
@laxmikandivalasa can you just check kid section it's taking lots of time

**Comment by laxmikandivalasa** [comment]
@Tejashri-Taral what does it mean?
I've checked them

**Comment by Tejashri-Taral** [comment]
@laxmikandivalasa Preloader taking lots of time in kid section Please check it

**Comment by laxmikandivalasa** [comment]
@Tejashri-Taral can you check now again?

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Pull request merged**
