### PR TITLE
Navbar UI fix for Products component

### PR DESCRIPTION
**Pull request by sancharibansal**
Issue No. #199 
**Changes:**
Dropdown Arrow: Added a hover effect that displays an up-down arrow next to the "Products" menu for better user feedback.
Menu Design: Improved dropdown styling with better padding, background color, and box shadow for enhanced usability.
Code Cleanup: Removed redundant CSS rules for improved maintainability.

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Resolve issue as well as mention issue_no

**Comment by sancharibansal** [comment]
> Resolve issue as well as mention issue_no

Done

**Comment by Tejashri-Taral** [comment]
Resolve the conflicts

**Comment by sancharibansal** [comment]
> Resolve the conflicts

Done

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Please check this-
image

**Pull request closed without merging**
