### PR TITLE
added gsap ane enhanced the navbar also 

### LINKED ISSUE #69: enhanced the home page
Objective: I propose enhancing the navbar like this
https://github.com/user-attachments/assets/f6aabd48-4bda-4905-856a-362cd43cd31d
2nd objective :I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback

### PR DESCRIPTION
**Pull request by priyashuu**
fixes #69

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
You have made unnecessary changes your task was to : 
- enhance the navbar like video provided (you have add unnecessary section in navbar which were not in it earlier)
- On existing navbar adding text animation using gsap.

**Comment by Tejashri-Taral** [comment]
Please make the changes as #69

**Comment by priyashuu** [comment]
ok  , i will try my best , the video i provided it is jsx file , with some js  frameworks , ex framer motion , so for me its diffcut to animate similar like this in html and css , ill try my best ..

**Comment by priyashuu** [comment]
@Tejashri-Taral is it good ?

**Comment by Tejashri-Taral** [comment]
I told you not to change the navbar links only make your animation as per that issue description
Before:
image

After:
image

Let me know if you can make the changes.

**Comment by Tejashri-Taral** [comment]
@priyashuu Some changes require as you can see:

https://github.com/user-attachments/assets/753d5884-0a08-4803-878c-a21374cb345b

Also there are lot of conflicts, You can make new PR

**Comment by priyashuu** [comment]
its done mam , please check it ,tell me if u need anything else

**Review by Tejashri-Taral — COMMENTED** [review]
Hi @priyashuu , Merging this PR after you have made new commits and resolved conflicts will affect the website. Because, I did the code review and found out that you removed some of the existing code like for ex, you removed the dropdown feature for the products link in the navbar. 

That is why, earlier I told you to make a new PR so that it'll be easy for you and the contribution you are making will be done. Hope you understand. 
Please make the requested changes and make new PR (also pull current changes first.)

**Pull request closed without merging**
