### PR TITLE
fixed featured section issues

### PR DESCRIPTION
**Pull request by SumaLatha2023**
### Issue: Improper Display of Featured Section and Empty Button Elements

The featured section of the website had several issues affecting its visual appearance and usability:
- **Misaligned Layout**: The elements within the featured section were not displaying properly on different screen sizes, leading to a poor user experience on mobile and tablet devices.
- **Unnecessary Buttons**: There was an extra, unnecessary empty button next to the "Shop Sunglasses" and "Shop Clothing" sections, which cluttered the interface.
- **Animations**: The hover animations for the images were present but inconsistent and lacked fluidity, reducing the visual appeal of the section.

#### Before: 

Screenshot 2024-10-18 172540

Screenshot 2024-10-18 184812

#### After:

[Watch the video](https://github.com/user-attachments/assets/fad1f7fe-e4c4-466c-b84c-576b60805b18)

Screenshot 2024-10-18 185013

### Fixes Implemented

1. **Responsive Design**: 
   - Adjusted the layout for mobile, tablet, and desktop views using **media queries**. The sections now dynamically resize and stack vertically on smaller devices, ensuring a seamless user experience regardless of screen size.

2. **Elimination of Unnecessary Buttons**:
   - Removed the **unnecessary empty buttons**, cleaning up the interface and improving the visual hierarchy of the page.
   
3. **Button and Font Size Adjustments**:

4. **Improved Hover Animations**:
   - Improved the **hover animations** for images within the featured section, adding a smoother scaling effect when users hover over each item. 

### Impact

These changes have significantly improved the usability and visual appeal of the featured section. The section now:
- **Displays consistently** across all device sizes, providing an enhanced user experience for mobile, tablet, and desktop users.
- Has a **cleaner interface** with the removal of unnecessary elements, improving the overall design.
- **Engages users** with smooth animations and well-sized buttons that make navigation intuitive and pleasant.

By addressing these key issues, the featured section is now fully optimized for both functionality and aesthetics.

### CODE REVIEW

**Comment by SumaLatha2023** [comment]
@Tejashri-Taral kindly review and merge the request

**Review by hars-21 — CHANGES_REQUESTED** [review]
image


Shop sandals box is overflowing out of the screen. Please fix it. @SumaLatha2023

**Comment by SumaLatha2023** [comment]
check it out .. 
Screenshot 2024-10-20 124845

**Comment by hars-21** [comment]
@SumaLatha2023  Please fix the merge conflicts

**Comment by SumaLatha2023** [comment]
Merged

**Review by hars-21 — CHANGES_REQUESTED** [review]
@SumaLatha2023 There is too much white spacing that is not needed. You can reduce the size of the images too.

image

**Comment by SumaLatha2023** [comment]
@hars-21 I have tried that but I couldn't find where the styling of the images is as the code was not as organized
Let me know if I had to work on it

**Comment by Tejashri-Taral** [comment]
@SumaLatha2023 Where were you assigned? as I notice that you are not assigned to it 
Read #90 
due to guidelines we can't merge it 
sorry for inconvenience cause by @hars-21

**Pull request closed without merging**
