### PR TITLE
Fixed Wishlist icon, name and price highlighting and hover animation timing 

### LINKED ISSUE #13: Improve Wishlist Icon Design, Product Info Visibility, and  Hover Animation Smoothness
Description:
The names and prices of the products in the image look quite small and blend into the background. For an e-commerce site, product names and prices should be easy to spot, as they are crucial pieces of information for users.
The "ADD TO WISHLIST" button is too prominent. A smaller, more subtle icon (like a heart in the corner) would keep the focus on the products.
The hover animation on product images feels unsmooth. Adjusting CSS transitions (e.g., transition-duration and transition-timing-function) can improve this.

Steps to Reproduce:
Hover over any product image and observe the Wishlist button and animation, look at the name of the product and it's price it don't stand out as much as it should be.

Expected Behavior:
A subtle Wishlist icon and a smoother hover animation for a better user experience.
The product name and price should stand out more with larger text, bold font, and better contrast to make them easier to notice.

Screenshot 2024-10-01 213436

### PR DESCRIPTION
**Pull request by chiragsaini96**
I did changes in Wishlist icon , name & price highlighting and hover animation on images 
Fixes #13 

.  Wishlist icon : Before it was standing out a little too much so i replaced the text "Add to Wishlist" with a heart icon. There was a single class assigned to all the buttons(mostly) on the website that's why i gave them a special id to make the changes , i could give them another class instead of a id if you want to make that change you can let me know. Also i changed its position from bottom-center to bottom-left so that it don't distract the user.
 
.  Name and price highlighting : To highlight the name and price i changed their font-weight. i gave the name more weight than the price so that the user don't give the price much priority than the product itself  that's also the reason i also changed the price color to a little lighter. In the end i changed its alignment to center so that the name and price feel more connected to their respective product-pic.

.  Hover animation : I only changed the timing just a little bit which make the transition bit slower so the user doesn't feel in a hurry and takes their time to browse from the list.(i don't know if the reason makes any sense but i though it would look nice so i just gave it a little touch)

Thankyou for this project.
and Please tell me if you want to make any kind of change in it.

Screenshot 2024-10-02 133744

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts

**Comment by chiragsaini96** [comment]
> Please resolve conflicts

Thanks for the heads-up I've resolved the conflicts and pushed the changes. Please let me know if anything else needs attention

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
That's nice!
Can you just add matching color of products?

**Comment by chiragsaini96** [comment]
> That's nice! Can you just add matching color of products?

Do you mean changing the name based on the product color or something else I just want to make sure I understand before proceeding.

**Comment by Tejashri-Taral** [comment]
@chiragsaini96 Yes

**Comment by chiragsaini96** [comment]
> @chiragsaini96 Yes

I've made the changes. Let me know if you need anything else

**Pull request merged**
