### PR TITLE
upated cart page

### PR DESCRIPTION
**Pull request by Veda273**
I have made the following changes:
1)Properly aligned and styled the item details and heading for improved readability.
2)Added a hover effect to the cart items to enhance interactivity.
3)Implemented a dynamic item counter that updates automatically based on the cart contents.
4)Introduced a notification pop-up for item removals to inform users in a subtle, non-intrusive way.
here is a preview:

https://github.com/user-attachments/assets/64d38f28-506e-424b-b3da-078b5e8d7e44

@Tejashri-Taral please, review my pr.. If you find the changes satisfactory, please consider assigning the Level 2 label. Thank you!

### CODE REVIEW

**Comment by Veda273** [comment]
@Tejashri-Taral I was assigned this as part of issue #761 ..
Any updates?

**Comment by Tejashri-Taral** [comment]
Yes

**Comment by Tejashri-Taral** [comment]
Yes

**Comment by Veda273** [comment]
@Tejashri-Taral I made another pr from the previous branch.. please check that

**Pull request closed without merging**
