### PR TITLE
Made the nav bar sticky

### PR DESCRIPTION
**Pull request by Varshitha713**
Screenshot 2024-10-07 141500

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please mention issue no with # eg.#123

**Review by Tejashri-Taral — COMMENTED** [review]
As it's not enough to give level1 I'm giving you one more task
Please Change the color of Scroll Progress Bar

**Comment by Tejashri-Taral** [comment]
@Varshitha713

**Review by Tejashri-Taral — COMMENTED** [review]
Where is scroll bar? Please update branch and Change the color of Scroll Progress Bar 
375529081-b7516616-9cae-48c7-9c3c-011c94390612

**Comment by Varshitha713** [comment]
This time i created a sub-branch  called nav-bar  to work on the scroll bar and when i try a PR from that branch it is showing like this...
Screenshot 2024-10-12 183824
Screenshot 2024-10-13 152748
if you understood this could you help me overcome this problem ...I tried to merge the changes that i made in that branch to my main branch but it isn't getting updated!!


I added the scroll -progress bar 
when we scroll it look like this👇
Screenshot 2024-10-12 182319
on hover the scroll bar looks something like this👇
Screenshot 2024-10-12 182522

**Comment by Varshitha713** [comment]
How come the PR is closed? Could we open it again?

**Comment by Varshitha713** [comment]
how come the PR is closed?

**Pull request closed without merging**
