### PR TITLE
add dark and light theme to the website

### PR DESCRIPTION
**Pull request by ruchikakengal**
#79 fixed 
Screenrecording

https://github.com/user-attachments/assets/db785f2b-a0fe-43f4-9ae9-67a6a7c08698

### CODE REVIEW

**Comment by ruchikakengal** [comment]
@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Dark mode is not work properly check it once

**Comment by Tejashri-Taral** [comment]
@ruchikakengal Any update?

**Comment by Tejashri-Taral** [comment]
As this issue is not resolved for more than a week, and I am assigning it to other contributors

**Pull request closed without merging**
