### PR TITLE
Added hover effect to quick links section

### LINKED ISSUE #231: Add Hover Effect to "Quick Links" in Footer
In the footer section of the website, the "Quick Links" are not clearly identifiable as clickable links because they lack a hover effect. This causes confusion for users as it is difficult to distinguish them from regular text.

***********************************************************************************************************************************************
Problem:
The "Quick Links" section currently looks like regular text rather than clickable links.
There is no visual indicator (such as a color change or underline) when hovering over the links.
This can lead to a poor user experience since users might not realize these are links.

***********************************************************************************************************************************************
Name : Shrihari Bhilwadikar
Participant Role : GSSOC, Hacktoberfest 2024

***********************************************************************************************************************************************
I would like to work on this issue. Please assign it to me.

### PR DESCRIPTION
**Pull request by Shrihari25-hub**
closes #231 
- Implemented a hover effect for the Quick Links in the footer section.
- Applied a circular shape hover effect by adjusting padding and border-radius.
- Text color changes to white and the background color changes to black when hovered.
- Added a smooth transition for color, background, and slight upward movement to enhance user interaction.

********************************************************************************************************************

### CODE REVIEW

**Comment by Shrihari25-hub** [comment]
Hi, could you please add the GSSOC, Hacktoberfest 2024 labels to this pull request. 
I notice that I see two notifications for the same contribution—one where I'm listed as the author and another as assigned. 
WhatsApp Image 2024-10-10 at 18 07 25 (1)

Thank you!

**Review by Tejashri-Taral — COMMENTED** [review]
As this is not suitable for level1 task. I'm adding a new task for you 

On hovering, An underline from left to right should be there in each link in footer in every page's footer.

**Comment by Shrihari25-hub** [comment]
I have completed the task. added left-to-right hover underline effect in each link in. i have also Implemented smooth transitions for a better user experience. Please review the changes.

**Comment by Tejashri-Taral** [comment]
@Shrihari25-hub
Don't make that effect on social icon

**Comment by Shrihari25-hub** [comment]
@Tejashri-Taral Done! I have remove the underline hover effect on social icons

**Review by Tejashri-Taral — COMMENTED** [review]
Add hover effect in all the pages where footer is present

**Comment by Shrihari25-hub** [comment]
Sure, I will add hover effects to all the pages. I just have one question, inside the Contact Us section in the footer only the "About" and "Contact Us" pages have clickable links for the email and phone number . On the other pages, it's just text with no clickable links. Should I add hover effects for clickable links only, or should I make changes to every HTML page where the links are not clickable, and then add hover effects to all the pages?
@Tejashri-Taral

**Comment by Shrihari25-hub** [comment]
In the Home, features, products pages , some links were not clickable, I have made those links clickable and have add hover effect to all links in footer.

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Pull request merged**
