### PR TITLE
updated the login and signup form

### LINKED ISSUE #566: The enhancement of sign up and login page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The sign up and login page can be enhanced by adding the password conditions like adding uppercase, lowercase, special characters. 
Continue with google , Github, twitter option for user friendly usage.
image
image

### Use Case

It looks a complete outlook to the webpage .

### Benefits

The user can have more advantages with this features.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by AADESHak007**
This PR Fixes #566 . 
I have updated the layout for both login and signup page .
I have also updated the effects on buttons for better interaction .
## Screenshots :
* BEFORE  :
Screenshot 2024-10-27 121553

* AFTER :
Screenshot 2024-10-27 140445
Screenshot 2024-10-27 140434

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts also don't change it keep as it is

**Comment by AADESHak007** [comment]
@Tejashri-Taral Do you want everything to be in a single line ?. If that is what you want then I can do that but it is not appealing and if you noticed that most of the websites follow this pattern .If we are putting everything in a column then the user gets the feeling that he/her has to fill a lot of columns which can reduce the User Experience .

I have resolved the conflicts though . If you still feel like changes should be done then be descriptive about the changes you want and I will do it surely .
Thank You

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Prev one is better than current

**Comment by AADESHak007** [comment]
> Prev one is better than current

I ll make changes in the previous layout and will raise a PR by today .

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
