### PR TITLE
Updated the readme file with the featured in, repo review table and our contributors

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Updated the readme file with the featured in, repo review table and our contributors

closes :- #346 

@Tejashri-Taral Please review this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@Tejashri-Taral First merge this PR :- #576 then this one both are mine only.

**Review by hars-21 — APPROVED** [review]
Approved!

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by Tejashri-Taral** [comment]
Please add link in footer I'll increase level

**Review by MastanSayyad — COMMENTED** [review]
After reviewing the code I'm Reducing the level from `level 3` to `level 1` for this as PR #576 is also about Contributors page and already got `level 3`

Thank you!

**Pull request merged**
