### PR TITLE
added the functionality to search and user icon

### PR DESCRIPTION
**Pull request by bhavanireddy57**
Pull request
Issue no: 8  closes
Added the functionality to the search and user icon in the nav bar by adding features in html,css files.

### CODE REVIEW

**Comment by bhavanireddy57** [comment]
please review and let me know if any changes are required.

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts

**Comment by bhavanireddy57** [comment]
> Please resolve conflicts

Can you once again check it and let me know

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
See this and also add screenshot or video what you have done

**Comment by Tejashri-Taral** [comment]
I am not able to see any changes in preview please share the video

**Comment by bhavanireddy57** [comment]
I just saw user login is already modified so i added a search icon functionality to my modified code.can you review it and let me know.
Screenshot 2024-10-07 162640

**Comment by bhavanireddy57** [comment]
When i click on search icon then it opens like shown in an image.Can you let me know after reviewing it.

**Comment by Tejashri-Taral** [comment]
Good @bhavanireddy57!

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by bhavanireddy57** [comment]
> Good @bhavanireddy57!

Thank you

**Pull request merged**
