### PR TITLE
add mens.html and womens.html file#43

### PR DESCRIPTION
**Pull request by Abhishek89chauhan**
#43 
i have added shopping section for mens and womens seperatly and do change in navbar adding men and womens feature for selecting seperatly

### CODE REVIEW

**Comment by Abhishek89chauhan** [comment]
please provide a level and merge this pr

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
I liked the changes you made.

Please make the bellow changes:
- Move Women and men links In product section by making it drop down.

image

- Convert Rs. into dollar for all products
image

**Comment by Abhishek89chauhan** [comment]
Thank you for asking me to make these changes. I will keep your words in mind and will implement the changes you suggested.

**Comment by Abhishek89chauhan** [comment]
i did changes as you told please check that

**Comment by Tejashri-Taral** [comment]
@Abhishek89chauhan Awesome!👏

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
