### PR TITLE
solved issue #419

### LINKED ISSUE #419: Scroll to top button availability
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Scroll to top button is not available on many pages .

### Add Screenshots / Video Clip

_No response_

### What browsers are you seeing the problem on?

_No response_

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Devanshu1603**
Added Scroll to top button on contact and about us page . @hars-21 Please review the PR and merge it accordingly and please also add levels accordingly.

closes #419

### CODE REVIEW

**Review by Tejashri-Taral — COMMENTED** [review]
Add it into footer pages also

**Comment by Tejashri-Taral** [comment]
No @Devanshu1603 in footer pageas like terms and condition,privacy policy

**Comment by Devanshu1603** [comment]
@Tejashri-Taral  have added the go to top button in footer also in quick links section . please merge the PR now.

https://github.com/user-attachments/assets/ce5a9819-d7a9-4359-b2ad-9476b548bd82

**Comment by Tejashri-Taral** [comment]
Please resolve the conflicts

**Comment by Devanshu1603** [comment]
@Tejashri-Taral  i have solved the conflicts , now please merge the PR.

**Comment by hars-21** [comment]
@Devanshu1603 Again, there is conflict. Please resolve it.

**Comment by Devanshu1603** [comment]
@hars-21  i have solved the conflicts , please merge it now

**Comment by Tejashri-Taral** [comment]
I suggest you to make a new PR

**Pull request closed without merging**
