### PR TITLE
Updated CSS of All Pages to Align `Images` And `Add to Cart` Button

### LINKED ISSUE #363: Irregular `Image Size` And Improper alignment in product pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Align Images and Button:
- Ensure that all images have a uniform size and aspect ratio.
- Use CSS to align the `Buy Now` buttons with the images.

### Add Padding Around Images:
Add padding to the images to create a more professional appearance.

@Tejashri-Taral please assign me the task

### Add Screenshots / Video Clip

Screenshot 2024-10-13 173037

### What browsers are you seeing the problem on?

Chrome

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
- removed all stretching and distortions of image using object, fit aspect ratio & other CSS features
- Align `Add to cart` button where ever needed with proper bottom margin in the card
- Corrected this issue by checking all pages
- aligned image, text, cart, description, etc. of a card with side card 
- where ever keeping same dimension of images were creating issue in display of product => aligned image and add to cart in a line for all side by side card to make it more user friendly
 @Tejashri-Taral please review this pr
 ## closes #363 
image

image

image
image

image

image

@hars-21

### CODE REVIEW

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral @hars-21 check this out

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral please review this pr

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral please review this

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
You have changed navbar

**Comment by Adarsh-Chaubey03** [comment]
> image
> You have changed navbar
I'll take care of the corrections.

**Comment by Tejashri-Taral** [comment]
Alright! also you have deleted some women's section clothes Please check it

**Pull request closed without merging**
