### PR TITLE
This Pull Request introduces the Add to Wishlist feature, which allows users to wishlist their items with the following functionalities:

### PR DESCRIPTION
**Pull request by sanjuyadavvv**
Add to Wishlist:
Users can click on the wishlist icon to add items to their wishlist.
The wishlist icon will display a popup showing the count of items wishlisted.
Remove from Wishlist:
Users can remove an item from their wishlist by clicking on the wishlisted button.
When an item is removed, the count of wishlisted items will decrease by 1.
Implementation Details:
DOM Manipulation: Utilized to dynamically update the wishlist count and manage the UI elements.
Event Listeners: Added to handle click events for adding and removing items from the wishlist.
Array Management: An array is used to track the wishlisted items, ensuring that a single item can only be wishlisted once.

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Before:
WhatsApp Image 2024-10-04 at 23 11 09_e2b27454

After:
WhatsApp Image 2024-10-04 at 23 10 53_468d8813

Keep as it is

**Comment by Tejashri-Taral** [comment]
I like the changes you made Please make the requested changes and resolve the conflicts.

**Comment by sanjuyadavvv** [comment]
Im not getting a good arrow line icon  . They are really short .please
 Help me with the issue

**Comment by Tejashri-Taral** [comment]
I'm not talking about arrows I just highlighted that dont change the styling of those buttons. Keep those as it is.

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv if you have any query you can ask

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv any update?

**Comment by sanjuyadavvv** [comment]
Yes i did the requested  changes and submitted some issues as well

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Little bit change require
image

Also you have changed that buttons:
image
keep it as it is

**Comment by sanjuyadavvv** [comment]
okayyy .Thanks for briefly explaining

**Comment by sanjuyadavvv** [comment]
I have made the changes please check if they are fine

**Comment by Tejashri-Taral** [comment]
You have remove lot of lines of codes
navbar also changed Please don't reduce code just add your code

**Comment by sanjuyadavvv** [comment]
Please review the recent commits

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
Don't remove number lot of lines it affects to the website
Also check "Explore More" button keep it's styling as it is

**Comment by sanjuyadavvv** [comment]
should i clone the project once again and then do the  changes as this is
getting messy

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv You  should  update branch no need to clone again
- Click on sync button then update
- 
image

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv Please make changes asap

**Comment by sanjuyadavvv** [comment]
Heyy . I did some changes  please check them

**Comment by Tejashri-Taral** [comment]
@sanjuyadavvv How?

**Pull request closed without merging**
