### PR TITLE
made explore more interactive

### PR DESCRIPTION
**Pull request by Veda273**
issue no: #761 
1)I added id to feature section and onclick functionality to explore more button to navigate to feature section on click.

here is the preview:

https://github.com/user-attachments/assets/053ccd5e-e7b1-4f2e-aa8a-196bff10ecc8

@harikasayani , please review my pr..

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
As this task is not level1 task
Can you add webpage containing some cool products ?

**Comment by Veda273** [comment]
@Tejashri-Taral sorry for the previous mistake 

https://github.com/user-attachments/assets/da25d2ca-5c51-4656-9236-ba23bba9d6ec

now it is linked to shop clothing page..

**Comment by Veda273** [comment]
@Tejashri-Taral  if this can't can be considered as level-1 task, I am willing to work on redesigning the cart page..
image

**Comment by Tejashri-Taral** [comment]
ok, proceed!

**Pull request merged**
