### PR TITLE
Added Accessories page

### PR DESCRIPTION
**Pull request by Annapoornaaradhya**
Related to ISSUE #390 
Added Accessories section to the website with trendy accessories that users can buy. It makes very attractive when people can buy the matching and trending accessories along with the clothes.
This is the page I have Added

https://github.com/user-attachments/assets/84c03d5b-6a89-4cc3-8eb3-83539ea49600

@hars-21 @Tejashri-Taral Please do assign this under gssoc-ext and hacktoberfest-accecpted and atleast  level 3
Thank You

### CODE REVIEW

**Comment by hars-21** [comment]
@Annapoornaaradhya Please make the required changes:
1. Make the headings larger
2. add spacing between product description, title, price, and buttons
3. centre the add to cart buttons
4. it would be great if you could bind products in the card form (optional).

**Comment by Annapoornaaradhya** [comment]
Sure I will do it.
I actually kept the same template as women section as it would look uniform throughout.
I will update the page and submit again
Thank you

**Comment by Annapoornaaradhya** [comment]
@hars-21 can You please check now I have made changes

**Review by Tejashri-Taral — COMMENTED** [review]
@Annapoornaaradhya I'm not able to see accessories page into he website
Where did you add it?

**Comment by Annapoornaaradhya** [comment]
@Tejashri-Taral It is under products in the drop down

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Comment by Annapoornaaradhya** [comment]
@Tejashri-Taral I would be grateful if you can please change the level to level 3 as I have taken much efforts to search for the right accessories to match with the theme of the webpage and have created a new feature altogether and added a whole extra page in the website.
Thank you

**Comment by Annapoornaaradhya** [comment]
Thank you @Tejashri-Taral

**Pull request merged**
