### PR TITLE
Add to cart functionality

### PR DESCRIPTION
**Pull request by Pallavi-Mukalla**
I made the add to cart button responsive and also the added elements will be displayed in the cart. we can increase and decrease the item count in cart also.

https://github.com/user-attachments/assets/bcf96b91-3754-45a1-aef6-2a1e9f8f8530

I made the changes only for the women section.

### CODE REVIEW

**Comment by Pallavi-Mukalla** [comment]
please review my changes

**Comment by Pallavi-Mukalla** [comment]
please review my changes and accept my pull request

**Review by Tejashri-Taral — COMMENTED** [review]
Add this functionality in all pages kids,mens and accessories

**Comment by Pallavi-Mukalla** [comment]
I'm currently unable to work on all pages, so I've only completed the women's page. It may be best to assign the other pages to someone else who can handle them sooner. I apologize for the inconvenience. Also, I request that you please merge my PR.

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
