### PR TITLE
Alignment of text and image on mobile screens(issue #441)

### LINKED ISSUE #441: [Bug]: Alignment of text and image on mobile screens
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The images are not visible clearly on different screen sizes.
The about us page alignment of text and image is looking odd.
The content of footer section is overlapping each other.

### Add Screenshots / Video Clip

Screenshot (95)
Screenshot (98)

### What browsers are you seeing the problem on?

_No response_

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue [Optional]
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Ishika-Singhal**
closes #441 

I have made the about page responsive by making the header responsive and visible on all the devices screen.
Also align the text and image in correct format for different device screens .

before:
Screenshot (102)

after:
Screenshot (100)
Screenshot (104)

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Navbar is completely changed Please keep it as it is

**Comment by Tejashri-Taral** [comment]
Any update or should I close PR?

**Comment by Ishika-Singhal** [comment]
yes ,I am working on it .

**Comment by Ishika-Singhal** [comment]
i have now only changed the alignment and footer overlapping issue and not changed header.
@Tejashri-Taral please review

**Review by hars-21 — CHANGES_REQUESTED** [review]
image

For small devices, image and some content is overflowing from the screen, please fix it.
Currently, text is taking more space vertically, so try reducing padding to fit the text.

**Comment by Tejashri-Taral** [comment]
It's been more than a week also You took so much time even after requesting changes. Someone already fixed it in other PRs. Also to complete a simple task the limit Is max 5days

WhatsApp Image 2024-10-24 at 17 10 03_64a40eb0

**Comment by Tejashri-Taral** [comment]
I am closing this PR for these reasons. 
You can still find and raise new issues

**Pull request closed without merging**
