### PR TITLE
Resdesigned the contact page and made it responsive for all devices

### PR DESCRIPTION
**Pull request by achintyasrivastav**
Changed the contact page design and made it responsive for all the devices screens.

Changes : 
Screenshot 2024-10-16 150421
Screenshot 2024-10-16 150448
Screenshot 2024-10-16 150504

### CODE REVIEW

**Comment by harikasayani** [comment]
@achintyasrivastav  Looks Good To Me

**Comment by achintyasrivastav** [comment]
> @achintyasrivastav Looks Good To Me

Thanks! I request you to please assign this under the label of Hacktoberfest 2024 & GirlScript Summer of Code 2024.

**Comment by achintyasrivastav** [comment]
It's #423

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Comment by Tejashri-Taral** [comment]
@achintyasrivastav Good!

**Pull request merged**
