### PR TITLE
#534 Issue Solved - Added Translator Tool

### PR DESCRIPTION
**Pull request by PrAyAg9**
Solves - #534 

image

image

Japanese

image

image

image

image

### CODE REVIEW

**Review by hars-21 — APPROVED** [review]
Awesome

**Review by hars-21 — COMMENTED** [review]
Resolve conflicts @PrAyAg9

**Comment by PrAyAg9** [comment]
@hars-21  Check if it works all fine, I've resolved conflict but please check if website works all fine

**Review by hars-21 — APPROVED** [review]
Approved!

**Comment by PrAyAg9** [comment]
@hars-21  Why don't you merge it after approving, as more time you time you take more conflicts would arise it's been more than 3 days???

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
