### PR TITLE
Added icons to all pages of quicklinks

### PR DESCRIPTION
**Pull request by likitha-kapu**
Issue: #787 
Icons added to quicklinks
image

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts

**Comment by likitha-kapu** [comment]
@Tejashri-Taral there were no conflicts when I created a pull request....I have just added the icons

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
Your task was just add icons to all pages of quicklinks why you changes so many lines
There are lot of conflicts due to this

**Comment by likitha-kapu** [comment]
@Tejashri-Taral checkout once

**Comment by Tejashri-Taral** [comment]
Can't merge it will break the UI

**Comment by Tejashri-Taral** [comment]
Create a new PR before 7pm

**Pull request closed without merging**
