### PR TITLE
Added the Cursor Trail Effect

### PR DESCRIPTION
**Pull request by Piyush01-672**
The Cursor Trail Effect is added to improve UI.  A small black/white circle follows the cursor as it moves across the page, creating a more engaging UI.

### CODE REVIEW

**Comment by hars-21** [comment]
Please resolve the merge conflicts

**Comment by Piyush01-672** [comment]
@hars-21 
Hello, I've resolved the conflict, now it do not have any conflicts.

Kindly merge it and assign me the labels too!!

Thank you!!

fixes: #367 
image

**Review by Tejashri-Taral — COMMENTED** [review]
Please add video as I am not able to see any cursor effect

**Comment by Tejashri-Taral** [comment]
@Piyush01-672 There are so many conflicts Please make a new PR

**Pull request closed without merging**
