### PR TITLE
Added the contributors page

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the contributors page to the website with sleek ui, matching the theme of the website, integrated footer and navbar in it, fully responsive over all screen sizes, dynamic ui updates as the new contributors are added the repository and best practices while coding.

So i think it deserves a level 3 for my efforts on this page.

closes :- #343 

https://github.com/user-attachments/assets/ea574347-dc48-40b2-887f-df944f4fd7bb

https://github.com/user-attachments/assets/55892d98-20c8-4512-be7f-abd321dbd044

@Tejashri-Taral Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Review by hars-21 — COMMENTED** [review]
Good Work @tarunkumar2005 . Please link this page in the home page of the website.

**Comment by tarunkumar2005** [comment]
@hars-21 You can check i have added the link in the footer "Our Contributor".

**Comment by tarunkumar2005** [comment]
@hars-21 @Tejashri-Taral Please add labels such as gssoc 2024 ext, hacktoberfest and level.

Added the contributors page to the website with sleek ui, matching the theme of the website, integrated footer and navbar in it, fully responsive over all screen sizes, dynamic ui updates as the new contributors are added the repository and best practices while coding.

So i think it deserves a level 3 for my efforts on this page.

**Comment by tarunkumar2005** [comment]
@hars-21 @Tejashri-Taral Please add labels to it ???

**Comment by Tejashri-Taral** [comment]
@tarunkumar2005 not able see in the footer please add link of it

**Comment by tarunkumar2005** [comment]
@Tejashri-Taral See this our contributors this is it :- 

image

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Review by MastanSayyad — COMMENTED** [review]
It's fine

**Pull request merged**
