### PR TITLE
Make the about page responsive

### PR DESCRIPTION
**Pull request by Ibrangrd**
Fixed issues number #366 
1.Make the About page responsive
2. Also add some colour to  the text .
3. Adjust font-size.
Screenshot (285)

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Mention issue no.

**Comment by harikasayani** [comment]
@Ibrangrd, Please resolve conflicts.

**Comment by Ibrangrd** [comment]
ok , i will do it

**Comment by Ibrangrd** [comment]
Now , there is no conflicts . so please accept it .

**Review by hars-21 — CHANGES_REQUESTED** [review]
image


Please fix this. @Ibrangrd

**Comment by Ibrangrd** [comment]
I fix the issue . so accept it 
Screenshot (376)

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
