### PR TITLE
[Feat]: Add Hover Effect to Main Heading for Dynamic Appearance

### LINKED ISSUE #635: [Feat]: Add Hover Effect to Main Heading for Dynamic Appearance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Feature Description**
I would like to request the addition of a hover effect to the main heading on the website's homepage. While the website is well-built and dynamic, the static main heading does not align with the rest of the site's interactive elements. Adding a hover effect will make the heading more engaging and consistent with the dynamic design of the website.
The main heading should have a smooth hover effect that changes its appearance when the user hovers over it. The hover effect can include a slight color change and scaling to make it more visually appealing.

Please assign this issue to me, and I would be happy to implement this feature.

### Use Case

This feature would enhance the user experience by adding a modern, interactive feel to the main heading. Users are more likely to be drawn to a dynamic element, especially when it's the main focus of the page.

### Benefits

- **Improved User Engagement**: The hover effect will grab users' attention and encourage interaction with the page.
- **Consistent Design**: Adding a hover effect to the main heading aligns it with the rest of the website’s dynamic design elements.
- **Modern Look**: It will give the website a more polished, modern appearance.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by sanchitc05**
Fixes #635

Before:
Screenshot (275)

After:
Screenshot (277)

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Not able to see any changes

**Comment by sanchitc05** [comment]
@Tejashri-Taral Please check now

**Comment by Tejashri-Taral** [comment]
@sanchitc05 Your changes not reflected on the website

**Comment by sanchitc05** [comment]
I have made the new pr for this @Tejashri-Taral 
https://github.com/Tejashri-Taral/TrendTrove-Ecommerce/pull/815

Please

**Pull request closed without merging**
