### PR TITLE
Adding Social handels on all pages

### PR DESCRIPTION
**Pull request by itskundanhere**
Screenshot 2024-10-13 181151

I have added the Social media Handel's ( LinkedIn, Github, Twitter, Instagram) on all the pages.

### CODE REVIEW

**Comment by itskundanhere** [comment]
Hii @Tejashri-Taral  please merge the my pull request

**Comment by Tejashri-Taral** [comment]
@itskundanhere add it into footer pages too

**Review by Tejashri-Taral — COMMENTED** [review]
@itskundanhere add it into footer pages too

**Comment by itskundanhere** [comment]
@Tejashri-Taral I have added in all the pages

**Review by Tejashri-Taral — COMMENTED** [review]
Terms and condition:
image
- return policy

And in about us page check it's position

**Pull request closed without merging**
