### PR TITLE
Adding Copyright Information to the Footer.

### PR DESCRIPTION
**Pull request by Orca-63**
I have added copyright information to the footer.

Screenshot 2024-10-03 100901

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please avoid making use of "Format doc" in vs code Just to Increase the no. of lines changed.
As I can below are the only change.

WhatsApp Image 2024-10-03 at 19 35 50_3322520e
WhatsApp Image 2024-10-03 at 19 36 00_4d6995fd

**Comment by Orca-63** [comment]
@Tejashri-Taral Apologies for the confusion. Actually, I have an extension installed in VS Code, that reformats the code automatically on saving the file, I'll make sure to disable it to avoid unnecessary formatting changes in the future. Could you please let me know if any further changes or improvements are needed.

**Comment by Tejashri-Taral** [comment]
It's Ok, For now I will approve the PR. 
Please make the Below link as it was before, as it may cause problem in future.

WhatsApp Image 2024-10-03 at 20 03 26_362304b6

**Comment by Orca-63** [comment]
@Tejashri-Taral Yes sure , actually I am new to open source contribution, so could you please tell me that I need to follow these steps for making the changes : 
1) Add and commit the changes on the same branch that I have already pushed.
2) Push the updated branch again to reflect the changes in the existing pull request.

Or do I need to follow some other steps?

**Comment by Orca-63** [comment]
@Tejashri-Taral Thanks for your guidance, I am making the changes.

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
