### PR TITLE
Added anchor for redirecting to homepage

### PR DESCRIPTION
**Pull request by shimmer12**
Added anchor for redirecting to homepage when clicking on TrendTrove , when clicking from pages like contact.
image
image

Please merge under Hacktoberfest accepted

### CODE REVIEW

**Comment by shimmer12** [comment]
@Tejashri-Taral please merge this

**Comment by Tejashri-Taral** [comment]
Please resolve the conflicts

**Comment by shimmer12** [comment]
@Tejashri-Taral 
Hi as I am beginner to contribution , it is showing this(image), what to do inorder to resolve conflict?
image

**Comment by shimmer12** [comment]
conflicts resolved

**Comment by Tejashri-Taral** [comment]
Hi @shimmer12 , I appreciate your contribution! However, according to the extended GSSoC guidelines, direct pull requests should not be made without first raising an issue and getting assigned to it.

Unfortunately, I can't merge PRs that haven't followed this protocol, so please make sure to raise an issue, get it assigned, and then proceed with your PR. 
Thank you for your understanding and cooperation!

**Comment by Tejashri-Taral** [comment]
I have to close this PR, Please make sure to follow guidelines

**Comment by shimmer12** [comment]
Solved issue #87

**Pull request closed without merging**
