### PR TITLE
updated slide class of banner section

### PR DESCRIPTION
**Pull request by aakanshimalik**
#526 
**Description**
Updated background image as originally it was not fitting the background and also not looking good . Also i have shifted h1 , p , button to the left.

**Type of issue**

- [x] Enhancement

**Screenshot of output**
image

### CODE REVIEW

**Review by hars-21 — CHANGES_REQUESTED** [review]
Don't Change the image. Only fix the overlapping text and handle responsiveness.

**Comment by Tejashri-Taral** [comment]
Any updates or should I close the PR?

**Comment by aakanshimalik** [comment]
image
 
Now the text is not overlapping with the image .

**Review by hars-21 — APPROVED** [review]

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
It's not looking good make it attractive

**Comment by aakanshimalik** [comment]
@Tejashri-Taral What change do you prefer?..plz explain a little

**Comment by Tejashri-Taral** [comment]
Currently, you just made the colour of the banner dull(like grey) but it was originally white + you have shifted the Heading to the left which was at the center.

Also, we don't require these changes in the banner, so to give you the points as a beginner contributor I am adding 2 simple tasks to you, you can make a new PR (by pulling the latest changes first) 
1. reduce the width of vertical scrollbar width as currently it is too thick. 
2. The scrollprogress bar was present but currently it is not present, so you can make it present there again.

**Comment by Tejashri-Taral** [comment]
let me know if you can do it, otherwise we need to close the PR

**Pull request closed without merging**
