### PR TITLE
Issue resolved #137

### LINKED ISSUE #137: Want to add feedback option
Feedback is very important nowadays for Ecommerce. So, I want to add that feature in your website.

Please assign this task to me under gssoc-ext and hacktober.

### PR DESCRIPTION
**Pull request by Kajalmehta29**
Please have a look. I made the requested changes

Screenshot 2024-10-06 155920
Screenshot 2024-10-06 155928

### CODE REVIEW

**Comment by hars-21** [comment]
Please resolve the merge conflicts @Kajalmehta29

**Comment by Kajalmehta29** [comment]
Merged conflicts resolved

**Comment by Kajalmehta29** [comment]
@Tejashri-Taral Please have a look and merge this. I have removed conflicts.

**Comment by Tejashri-Taral** [comment]
@Kajalmehta29 You have changed terms and condition page. please,check it once.

**Comment by Kajalmehta29** [comment]
Please have a look @Tejashri-Taral

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
