### PR TITLE
the scroll to top button has been adt ded at the about page .

### LINKED ISSUE #656: to add a scroll up button at about page
i would like to add a scroll up  button over the about page using some css and other properties
please assign me this issue under gssoc extd 24 , hactoberfest, level 2

### PR DESCRIPTION
**Pull request by 2004pra**
i have done the changes without disturbing the theme of the website 
the scroll to top button has been added carefully .
@Tejashri-Taral 
please make it level 2 if you can please ....
fixes #656

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Add it into all pages and also use arrow inside that black circle like main page

**Comment by 2004pra** [comment]
ok will be done today by 10 pm

**Comment by Tejashri-Taral** [comment]
Any updates or Should I close the PR?

**Comment by 2004pra** [comment]
It will be done today mam before it was Diwali and today I was travelling
back to my college so I will try to complete it till tommorow please just
last wait

**Comment by Tejashri-Taral** [comment]
Alright!

**Comment by 2004pra** [comment]
i am closing this pr and raising a new pr now

**Pull request closed without merging**
