### PR TITLE
changes in index.html and add feature and product section

### PR DESCRIPTION
**Pull request by shivamraj-2003**
add features section and product section in this website

### CODE REVIEW

**Review by hars-21 — CHANGES_REQUESTED** [review]
Please add navbar and footer in both the features and products page.

**Comment by shivamraj-2003** [comment]
I added a navbar and footer in features and product merge my pull request now

**Comment by hars-21** [comment]
@shivamraj-2003 Please resolve the merge conflicts

**Comment by shivamraj-2003** [comment]
> @shivamraj-2003 Please resolve the merge conflicts

How can I merge the conflicts

**Comment by shivamraj-2003** [comment]
I resolved the merge conflicts kindly merge my pull request now

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Read #90
You are not following guidelines

**Comment by Tejashri-Taral** [comment]
Read #90

**Pull request closed without merging**
