### PR TITLE
scroll up button added

### PR DESCRIPTION
**Pull request by ShrishtiSingh26**
Closes: Issue #28 
Title: add scroll to top button
Your Name: Shrishti Singh
Idenitfy yourself: Contributor in gssoc-ext and Hacktoberfest
Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
I have added the "scroll to top" button to the application. This feature will enhance user navigation, especially on pages with long content, allowing users to easily return to the top without manually scrolling.
image
image

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Please add icon of scroll to top button instead of text
like this:
image

**Comment by sriraghavi22** [comment]
Hey @Tejashri-Taral Can i work on this?

**Comment by ShrishtiSingh26** [comment]
@Tejashri-Taral I have made the requested changes .

image

**Comment by Tejashri-Taral** [comment]
@ShrishtiSingh26 Please resolve the conflicts

**Pull request closed without merging**
