### PR TITLE
navbar ui improved

### PR DESCRIPTION
**Pull request by dipeshkumar799**
I  improved the navbar. The navbar will be hidden while scrolling down, but I will make it reappear and stick to the top of the page as the user scrolls back up. Additionally, I will enhance the icons. When hovering over the cart, login, or search icons, the pointer will change to a cursor. I'll also make the icons increase in size when hovered over.

this is the issue number: #440 

https://github.com/user-attachments/assets/2bc9afd2-d5c0-4e76-8937-0c62b4c2748e

@Tejashri-Taral  :pls review my pull request and merge my changes

### CODE REVIEW

**Comment by harikasayani** [comment]
@dipeshkumar799 LGTM!

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
It's looks like to me.Please do changes

**Comment by dipeshkumar799** [comment]
Oh sry yr Tomorrow I fixed it @Tejashri-Taral

**Comment by dipeshkumar799** [comment]
there is little issue in this pull request ,i have fixed those and will make new pull request.

**Pull request closed without merging**
