### PR TITLE
Added feedback option.

### PR DESCRIPTION
**Pull request by Kajalmehta29**
I have added feedback option at the footer part so as to take reviews from the customer.
issue resolved- #137 

image

image

Please have a look.

### CODE REVIEW

**Review by hars-21 — CHANGES_REQUESTED** [review]
image

Don't add the feedback form in footer instead create a new section. Also, don't change the colours of links in footer.

**Comment by hars-21** [comment]
I guess you have not pushed your latest commit. Please check properly and make the changes

**Comment by Kajalmehta29** [comment]
Should i make a new PR?

**Comment by Tejashri-Taral** [comment]
@Kajalmehta29 You can

**Comment by Kajalmehta29** [comment]
Please check it i committed it to main.

**Comment by Kajalmehta29** [comment]
Screenshot 2024-10-06 155920
Screenshot 2024-10-06 155928

**Pull request closed without merging**
