### PR TITLE
Added toggle button

### PR DESCRIPTION
**Pull request by Srija-11**
### **Related Issue**
Fixes: #729 

### **Description**
 added toggle button

### **Type of PR**
- [x] Feature enhancement

**### Screenshots / videos (if applicable)**
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
without toggle-
Screenshot (174)

with toggle-
Screenshot (175)
Screenshot (176)

### **Checklist:**
- [x] I have made this change from my own.
- [x]  My code follows the style guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  My changes generate no new warnings.
- [x]  I have tested the changes thoroughly before submitting this pull request.

I have provided relevant issue numbers and screenshots after making the changes.
Please add GSSOC EXTD and level labels to the PR

### CODE REVIEW

**Review by Tejashri-Taral — COMMENTED** [review]
Add toggle button in the home page not in only about us

**Comment by Tejashri-Taral** [comment]
Any update?

**Comment by Srija-11** [comment]
> Any update?

Yeah yeah working on it

**Comment by Srija-11** [comment]
> Add toggle button in the home page not in only about us Also add button instead of text

it is a button on clicking it is toggling from light to dark mode

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
