### PR TITLE
enhanced the navbar

### LINKED ISSUE #69: enhanced the home page
Objective: I propose enhancing the navbar like this
https://github.com/user-attachments/assets/f6aabd48-4bda-4905-856a-362cd43cd31d
2nd objective :I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback

### PR DESCRIPTION
**Pull request by priyashuu**
fixes #69

### CODE REVIEW

**Comment by priyashuu** [comment]
mam please review it , tell me if anything else you need , please add levels also

**Comment by Tejashri-Taral** [comment]
Good @priyashuu 
There is little bit change require if you wish you can work otherwise it is ok

**Comment by priyashuu** [comment]
its done mam ,

**Comment by priyashuu** [comment]
Ma'am, could you kindly consider increasing the level? It took quite a bit of time to complete, so an adjustment would be appreciated. Of course, if it's not feasible, it's still good as it stands. Thank you for your understanding!

**Comment by Tejashri-Taral** [comment]
@priyashuu Great work!

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
