### PR TITLE
Enhanced About Page

### PR DESCRIPTION
**Pull request by Adarsh-Chaubey03**
- Improved layout
- added image section
Screenshot 2024-10-06 183005
@Tejashri-Taral

### CODE REVIEW

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
This color combination is not following the theme of website.
Can you try some other combination?

**Comment by Adarsh-Chaubey03** [comment]
Okk

**Comment by Adarsh-Chaubey03** [comment]
Tried Grey-White combination:
image
Happy to try other if this combination is not satisfactory @Tejashri-Taral

**Review by Tejashri-Taral — COMMENTED** [review]
please make sure that you follow the website theme. as the website follows white background theme. you can make the similar theme only also please replace those images with some better ones (as it looks like shopping mall currently) 

you can refer the terms and conditions page

**Comment by Adarsh-Chaubey03** [comment]
updated as suggest @Tejashri-Taral 
Screenshot 2024-10-07 220241

**Comment by Adarsh-Chaubey03** [comment]
@Tejashri-Taral  please review this

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
