### PR TITLE
Added anchor to webpages, fixed issue #87 

### PR DESCRIPTION
**Pull request by shimmer12**
- [x] Added the anchor to webpage\
- [x] Changed logo of some pages that only had texts to make it consistent
- [x] read contributing rules
- [x] solves issue #87 

https://github.com/user-attachments/assets/d0893758-9175-4870-9f64-2300648a3c42

@Tejashri-Taral  Hii I have done the changes, it would be great if you merge this under GSSOC extd, Level 2 , Hacktoberfest accepted .

Thank you so much !

### CODE REVIEW

**Comment by shimmer12** [comment]
@Tejashri-Taral  please merge this

**Comment by Tejashri-Taral** [comment]
Add it into footer pages also

**Review by Tejashri-Taral — COMMENTED** [review]
Add it into footer pages also

**Comment by shimmer12** [comment]
Done the changes required.

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by Tejashri-Taral** [comment]
@shimmer12 as per the guideline I can't increase level because you have just add link instead of word which is already present in the code

**Pull request merged**
