### PR TITLE
ENHANCING THE ACCESSORIES PRODUCTS SAME LIKE OTHER PAGES 

### PR DESCRIPTION
**Pull request by laxmikandivalasa**
resolved issue num  #565
@Tejashri-Taral You can check for any other issues
I'd like to take any other inputs!!

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please resolve the conflicts

**Comment by laxmikandivalasa** [comment]
can you check now? @Tejashri-Taral

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
You deleted some accessories product please do check and do not remove any product

**Comment by laxmikandivalasa** [comment]
https://github.com/user-attachments/assets/0cd05de3-46fd-4224-8980-95e839f67248

hey @Tejashri-Taral 
I've not removed any but just modified the existing products...
earlier there were total 24 products..
I've just enhanced them...(above I've added the video) 
can you check once again...

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
Consider adjusting the width of the boxes so that the number of items per row is consistent

**Comment by laxmikandivalasa** [comment]
@Tejashri-Taral the above video that I've sent is what i changed and its well organised
can you check again??

**Comment by Tejashri-Taral** [comment]
some row contains 4 product some 3
It should be consistent like each row should contain 4

**Comment by laxmikandivalasa** [comment]
My changes are like this for the page...I don't know what it is for you
https://github.com/user-attachments/assets/de216936-dee9-403f-8161-158764d0622b
so once again can I send the pr

**Comment by laxmikandivalasa** [comment]
can you check now @Tejashri-Taral ??

**Review by Tejashri-Taral — APPROVED** [review]

**Comment by laxmikandivalasa** [comment]
I was expecting level2 label for this
can you assign level 2 since There were many lines of code included!! 
@Tejashri-Taral

**Pull request merged**
