### PR TITLE
✨issue #372 solved contact page improved✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
Screenshot 2024-10-14 at 1 11 30 PM

the contact us page is improved.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can you please review this code , thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral can you please review this code , thank you!

**Comment by Tejashri-Taral** [comment]
Read the guideline #90

**Comment by T-Rahul-prabhu-38** [comment]
bro

**Comment by T-Rahul-prabhu-38** [comment]
issue #372 i mentioned it in the title.

**Comment by T-Rahul-prabhu-38** [comment]
@Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
Oh my bad, Mentor assigned you

**Review by Tejashri-Taral — APPROVED** [review]
Approved!

**Comment by T-Rahul-prabhu-38** [comment]
thank you.

**Pull request merged**
