### PR TITLE
Add login link to navigation in all  required pages

### PR DESCRIPTION
**Pull request by Kasaksaxena**
### Description
This pull request adds a login link to the navigation menu on the About and Contact pages of the TendTrove website. 

### Changes Made
- Updated about.html to include a login link in the navigation section.
- Updated contact.html to include a login link in the navigation section.

### Reason for Changes
The addition of the login link enhances the user experience by providing easy access to the login functionality from all pages, allowing users to navigate to their accounts quickly.

### Additional Information
Please review the changes and let me know if any further modifications are needed.

### CODE REVIEW

**Comment by hars-21** [comment]
Please mention issue no.

**Review by hars-21 — CHANGES_REQUESTED** [review]
Please add login page on every page (sandals, sunglasses, bags etc.) Check all the pages with navbar and update with the login page.

**Comment by Kasaksaxena** [comment]
> Please add login page on every page (sandals, sunglasses, bags etc.) Check all the pages with navbar and update with the login page.

ohk

**Comment by Kasaksaxena** [comment]
Title: Add Login Link to Navigation Menu

Description: This pull request implements a login link in the navigation menu across all pages of the application, including:

Home

About

Contact

Sunglasses

Bags

Sandals

And other relevant pages


Changes Made:

Added a "Login" link to the navigation menu to enhance user accessibility.



Testing:

Verified that the login link appears correctly on all listed pages.

Checked functionality to ensure it redirects to the login page as expected.


Additional Notes: Please review the implementation and let me know if any changes are needed.

**Comment by hars-21** [comment]
@Kasaksaxena  Please fix the conflicts

**Comment by hars-21** [comment]
@Kasaksaxena Please fix the conflicts

**Comment by Kasaksaxena** [comment]
again  i resolve the conflicts

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
