### PR TITLE
Responsive Navbar / Redesigned Navbar

### PR DESCRIPTION
**Pull request by Rahul-AkaVector**
## **Summary**
This PR addresses issue #285, where the current navigation bar does not adapt well to different screen sizes, particularly smaller devices like smartphones and tablets. I've redesigned the entire navigation bar to be fully responsive, with enhanced usability on mobile and desktop devices. This new design keeps the core essence of the previous navbar while improving its layout, making it easier to navigate across all screen sizes.

### 1. **Dropdown Menu (For Mobile Devices)**
- Implemented a dropdown menu that appears for smaller screens, making the navigation links easier to access in a compact format.

### 2. **Responsive Navbar**
The navigation bar adjusts smoothly to different screen sizes, offering a seamless experience on mobile, tablet, and desktop.

#### **Desktop View:**
- Increased navbar height for better visibility.
- Adjusted font size for clearer text.
- Positioned the 'TrendTrove' logo outside the container for a more prominent appearance.
- Added a search button, shopping cart button, contact button, and a person icon to the right.
- Changed hover effect for the 'Men/Women' dropdown to a rectangular shape (replacing the capsule effect).
- Redesigned the rounded container border to be thinner for a more refined look.

#### **Mobile View:**
- Implemented a hamburger menu that lists navigation links with icons aligned to the left of the hamburger.
- Added a 'cancel' or 'close' button for the dropdown/sidebar menu, improving user experience.
- The hamburger menu switches between being placed inside the capsule on desktop and aligned to the left on mobile.

### 3. **File Structure**
- Organized the navigation bar css code into separate navigationbar.css file in a navigation folder, ensuring it can be reused consistently across the entire site. This approach improves maintainability and scalability.

## **Visual Preview**
Here's a brief video showing the new responsive navigation bar in action, highlighting both the desktop and mobile views:

https://github.com/user-attachments/assets/29cd43f8-cee9-40f2-bd4c-ce8161354f9e

## **Additional Information**
- I’ve ensured that the new navbar follows best practices for responsive design, optimizing for performance and accessibility.
- If there are any additional changes or tweaks you'd like to see, feel free to let me know!

## **Pending Feedback**
@Tejashri-Taral , could you please review the new design and let me know your thoughts on this approach?

Looking forward to your feedback!

### CODE REVIEW

**Comment by hars-21** [comment]
@Rahul-AkaVector  Please resolve the merge conflicts

**Comment by Rahul-AkaVector** [comment]
@hars-21 check out and let me know any changes

**Comment by hars-21** [comment]
@Rahul-AkaVector Please resolve the merge conflicts

**Comment by Tejashri-Taral** [comment]
I'm closing this pr as there are so many conflcts.
Make new PR with required changes

**Pull request closed without merging**
