### PR TITLE
[Feat]: Designing Feedback Form Page and Adding Navbar and Footer to it. #639

### LINKED ISSUE #639: [Feat]: Designing Feedback Form Page and Adding Navbar and Footer to it.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Designing Feedback Form Page and Adding Navbar and Footer to it.**

1. Making the Feedback Form more Responsive and adding Styling to it.
2. Adding Navbar and Footer For Page Navigation.
3. Customizing input fields in Form.

### Use Case

1. giving user customize view of form.
2. its easy for user to interact with form.
3. giving them the Page navigation features by adding navbar and footer to the Feedback form page

### Benefits

1. User Interaction will be increase.
2. More Feedback will given by user.

### Priority

High

### Agreements

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC contributor
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by Baig-fatema**
### Description
This pull request implements a feedback form page with a clean and responsive design. It includes the following enhancements:

- **Feedback Form Design**: Created a user-friendly feedback form that captures user inputs such as name, email, satisfaction ratings, and suggestions. The form is styled with Bootstrap for responsiveness and aesthetics.
  
- **Navbar Addition**: Integrated a navigation bar at the top of the page for easy access to other sections of the website, improving overall user experience.

- **Footer Addition**: Added a footer containing copyright information and links to social media, enhancing the page's professionalism and providing additional navigation options.

### Features
- Responsive layout that adapts to different screen sizes.
- Attractive animations for form elements and text.
- Star rating system for user feedback.
- Validation for form inputs to ensure data integrity.

### Screenshots
*Insert relevant screenshots here to showcase the new design and features.*

### Related Issues
- Closes #639

### Testing
- Manually tested the feedback form to ensure all fields validate correctly.
- Verified responsive design on multiple devices and screen sizes.

### Checklist
- [x] Code compiles without errors.
- [x] New features have been documented.
- [x] All tests have been added/updated accordingly.
- [x] Code follows the project's style guidelines.

### Additional Notes
Please review the design and functionality of the feedback form, navbar, and footer. Any feedback or suggestions for improvements are welcome!
Screenshot (101)
Screenshot (102)

### CODE REVIEW

**Comment by Baig-fatema** [comment]
@Tejashri-Taral  Please Review and Merge it Also add my point to leader board.

**Review by hars-21 — CHANGES_REQUESTED** [review]
Please don't change navbar and footer and link the feedback page in the footer of home page. 

image

**Comment by Baig-fatema** [comment]
@hars-21  and @Tejashri-Taral  please Review the Changes i made commit for your requested canges.
**Added Link to Feedback form in home page footer**
Screenshot (105)
**Design Feedback page without changing Navbar and Footer**
Screenshot (103)
Screenshot (104)

**Comment by Baig-fatema** [comment]
@hars-21  and @Tejashri-Taral  Please Review it Add Following labels:

**1. **gssoc
2. gssoc ext
3. level 2
4. hacker to be fest
5. and add my points to leader board****

please

**Comment by Tejashri-Taral** [comment]
Please read #90 You are not assigned to work on it
Sorry for the inconvenience caused by @hars-21

**Comment by Baig-fatema** [comment]
@hars-21 ans @Tejashri-Taral   Please Review it and Merge. i know it was not assign to me but i really put my efforts to make it good.
Please!
Please assign this to me and add my points.
Sorry for the violating the #90. but i have made the PR but there was delay in getting assigned to the issue so i started working on it without getting assigned I am sorry for that.
But please it takes lots of efforts and time to make it better please.

**Pull request closed without merging**
