### PR TITLE
Adjusted Filter Box Sizes for Better UI

### PR DESCRIPTION
**Pull request by sriharsha0x1**
**Could you please add level tag.......** @hars-21 

BEFORE:
image

AFTER:
image

image

### CODE REVIEW

**Comment by sriharsha0x1** [comment]
@Tejashri-Taral Could you check this merge request

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image

Please do changes

**Comment by sriharsha0x1** [comment]
I noticed the layout adjustments you mentioned. However, I haven’t made any changes to the main layout; I only worked on the filter boxes. Everything appears fine from my side, and the layout issue might not be related to my recent updates. 

@Tejashri-Taral 

https://github.com/user-attachments/assets/d3761600-225a-415b-bba9-c4d30d8c4dcc

**Comment by sriharsha0x1** [comment]
could you please review it? If there’s anything else needed, just let me know @Tejashri-Taral

**Review by hars-21 — APPROVED** [review]
Approved!

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
