### PR TITLE
Testimonials

### PR DESCRIPTION
**Pull request by BVaishnavi15**
Added Testimonials section in home pages as per #148

### CODE REVIEW

**Comment by hars-21** [comment]
@BVaishnavi15 Please resolve the merge conflicts

**Comment by Tejashri-Taral** [comment]
@BVaishnavi15 Please resolve the conflicts.

**Comment by BVaishnavi15** [comment]
Yes. I get it as no conflicts. can you please verify it.

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Please check navbar you changed navbar

**Pull request closed without merging**
