### PR TITLE
adding navbar feature

### PR DESCRIPTION
**Pull request by ayushijainn111**
i fixed the navbar and the hero image positioning

resolving #2 

this is how it is 
previous

these are the changes i made
Screenshot 2024-10-02 110422

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
Please resolve conflicts also add issue no. which issue you are solving like # issue_no

**Comment by ayushijainn111** [comment]
okay will work on it asap

**Comment by ayushijainn111** [comment]
@Tejashri-Taral the conflicts are resolved and I mentioned the issue no.

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
As I have seen you have decrease font size in navbar. please increase it.

**Comment by ayushijainn111** [comment]
@Tejashri-Taral i made the required changes. please check the latest commit

**Review by Tejashri-Taral — APPROVED** [review]

**Pull request merged**
