### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by S7viks**
I created a profile page, and cart page with an add-to-cart functionality and also added a search bar, please check.
issue number: #52
image
image
image
image
image

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
@S7viks Please resolve conflicts

**Comment by S7viks** [comment]
@Tejashri-Taral please check now

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
Do not change navbar keep it as it is

**Comment by S7viks** [comment]
@Tejashri-Taral please check

**Review by Tejashri-Taral — CHANGES_REQUESTED** [review]
image
Please compare this with existing and make changes

**Comment by Tejashri-Taral** [comment]
Please make a new PR by pulling the new changes also mention issue no.

**Pull request closed without merging**
